# frozen_string_literal: true

source "https://rubygems.org"

gem "bluejay", path: ".."
gem "frozen_record"
gem "sorbet-runtime"
gem "zeitwerk"

group :development do
  gem "minitest", "~> 5.0"
  gem "pry"
  gem "pry-nav"
  gem "rake", "~> 13.0"
  gem "sorbet"
  gem "tapioca", require: false
end
