# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Bluejay::Builtin::Directives::Deprecated`.
# Please instead update this file by running `bin/tapioca dsl Bluejay::Builtin::Directives::Deprecated`.

class Bluejay::Builtin::Directives::Deprecated
  sig { params(reason: T.nilable(String)).void }
  def initialize(reason); end

  sig { returns(T.nilable(String)) }
  def reason; end
end
