# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Bluejay::Builtin::Directives::Skip`.
# Please instead update this file by running `bin/tapioca dsl Bluejay::Builtin::Directives::Skip`.

class Bluejay::Builtin::Directives::Skip
  sig { params(if_arg: T::Boolean).void }
  def initialize(if_arg:); end

  sig { returns(T::Boolean) }
  def if_arg; end
end
