# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Bluejay::Builtin::Directives::Include`.
# Please instead update this file by running `bin/tapioca dsl Bluejay::Builtin::Directives::Include`.

class Bluejay::Builtin::Directives::Include
  sig { params(if_arg: T::Boolean).void }
  def initialize(if_arg); end

  sig { returns(T::Boolean) }
  def if_arg; end
end
