# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Bluejay::Builtin::Directives::SpecifiedBy`.
# Please instead update this file by running `bin/tapioca dsl Bluejay::Builtin::Directives::SpecifiedBy`.

class Bluejay::Builtin::Directives::SpecifiedBy
  sig { params(url: String).void }
  def initialize(url:); end

  sig { returns(String) }
  def url; end
end
