# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Graph::Person`.
# Please instead update this file by running `bin/tapioca dsl Graph::Person`.

module Graph::Person::Interface; end
