# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Graph::PlayerInput`.
# Please instead update this file by running `bin/tapioca dsl Graph::PlayerInput`.

class Graph::PlayerInput
  sig { params(first_name: String, last_name: String).void }
  def initialize(first_name, last_name); end

  sig { returns(String) }
  def first_name; end

  sig { returns(String) }
  def last_name; end
end
