[package]
name = "ext"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4", features = ["rb-sys-interop"] }
rb-sys = "0.9"
once_cell = "1.17"
convert_case = "0.6.0"
itertools = "0.10.5"
bluejay-parser = { version = "0.1.0-alpha.1" }
bluejay-core = { version = "0.1.0-alpha.1" }
