[package]
name = "ext"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.5.3", features = ["rb-sys-interop"] }
rb-sys = { version = "0.9.75", features = ["global-allocator"] }
once_cell = "1.17"
convert_case = "0.6.0"
itertools = "0.10.5"
bluejay-parser = { git = "https://github.com/adampetro/bluejay", rev = "716dc10d784268e9db734e819b3e512ad5f667a1" }
bluejay-core = { git = "https://github.com/adampetro/bluejay", rev = "716dc10d784268e9db734e819b3e512ad5f667a1" }
bluejay-printer = { git = "https://github.com/adampetro/bluejay", rev = "716dc10d784268e9db734e819b3e512ad5f667a1" }
bluejay-validator = { git = "https://github.com/adampetro/bluejay", rev = "716dc10d784268e9db734e819b3e512ad5f667a1" }
