[package]
name = "ext"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magnus = { version = "0.4", features = ["rb-sys-interop"] }
rb-sys = "0.9"
once_cell = "1.17"
convert_case = "0.6.0"
itertools = "0.10.5"
bluejay-parser = { path = "../../bluejay/bluejay-parser" }
bluejay-core = { path = "../../bluejay/bluejay-core" }
