[package]
name = "ext"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.5.3", features = ["rb-sys-interop"] }
rb-sys = "0.9.72"
once_cell = "1.17"
convert_case = "0.6.0"
itertools = "0.10.5"
bluejay-parser = { git = "https://github.com/adampetro/bluejay", rev = "a6cb3b9c6f334f477838542bd64fe4a74e037c11" }
bluejay-core = { git = "https://github.com/adampetro/bluejay", rev = "a6cb3b9c6f334f477838542bd64fe4a74e037c11" }
bluejay-printer = { git = "https://github.com/adampetro/bluejay", rev = "a6cb3b9c6f334f477838542bd64fe4a74e037c11" }
bluejay-validator = { git = "https://github.com/adampetro/bluejay", rev = "a6cb3b9c6f334f477838542bd64fe4a74e037c11" }
