[package]
name = "bluejay-rb"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.5.3", features = ["rb-sys-interop"] }
rb-sys = { version = "0.9.77", features = ["global-allocator"] }
once_cell = "1.17"
convert_case = "0.6.0"
itertools = "0.10.5"
strum = { version = "0.24", features = ["derive"] }
indexmap = "1.9.3"
paste = "1.0"
bluejay-parser = { git = "https://github.com/adampetro/bluejay", rev = "5fd7d78710a0e601ce488de631d5ca9169c3876b" }
bluejay-core = { git = "https://github.com/adampetro/bluejay", rev = "5fd7d78710a0e601ce488de631d5ca9169c3876b" }
bluejay-printer = { git = "https://github.com/adampetro/bluejay", rev = "5fd7d78710a0e601ce488de631d5ca9169c3876b" }
bluejay-validator = { git = "https://github.com/adampetro/bluejay", rev = "5fd7d78710a0e601ce488de631d5ca9169c3876b" }
bluejay-visibility = { git = "https://github.com/adampetro/bluejay", rev = "5fd7d78710a0e601ce488de631d5ca9169c3876b" }
