[package]
name = "ext"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.5.3", features = ["rb-sys-interop"] }
rb-sys = { version = "0.9.77", features = ["global-allocator"] }
once_cell = "1.17"
convert_case = "0.6.0"
itertools = "0.10.5"
strum = { version = "0.24", features = ["derive"] }
bluejay-parser = { git = "https://github.com/adampetro/bluejay", rev = "f2e477b82acbf39b1e5b2e98d9a5bc72abcc1499" }
bluejay-core = { git = "https://github.com/adampetro/bluejay", rev = "f2e477b82acbf39b1e5b2e98d9a5bc72abcc1499" }
bluejay-printer = { git = "https://github.com/adampetro/bluejay", rev = "f2e477b82acbf39b1e5b2e98d9a5bc72abcc1499" }
bluejay-validator = { git = "https://github.com/adampetro/bluejay", rev = "f2e477b82acbf39b1e5b2e98d9a5bc72abcc1499" }
