[package]
name = "ext"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.5", features = ["rb-sys-interop"] }
rb-sys = "0.9.65"
once_cell = "1.17"
convert_case = "0.6.0"
itertools = "0.10.5"
bluejay-parser = { git = "https://github.com/adampetro/bluejay", rev = "9d7cbcbc3251365da1677a782c4e6e86be0424eb" }
bluejay-core = { git = "https://github.com/adampetro/bluejay", rev = "9d7cbcbc3251365da1677a782c4e6e86be0424eb" }
bluejay-printer = { git = "https://github.com/adampetro/bluejay", rev = "9d7cbcbc3251365da1677a782c4e6e86be0424eb" }
bluejay-validator = { git = "https://github.com/adampetro/bluejay", rev = "9d7cbcbc3251365da1677a782c4e6e86be0424eb" }
