# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Player`.
# Please instead update this file by running `bin/tapioca dsl Player`.

module Graph::QueryRoot::Interface
  abstract!

  sig(:final) { returns(String) }
  def resolve_typename; end

  sig { abstract.params(location: T.nilable(String)).returns(T::Array[Graph::Team::Interface]) }
  def resolve_teams(location); end
end
