# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Player`.
# Please instead update this file by running `bin/tapioca dsl Player`.

module Graph::Team::Interface
  abstract!

  sig(:final) { returns(String) }
  def resolve_typename; end

  sig { abstract.returns(String) }
  def resolve_name; end

  sig { abstract.returns(String) }
  def resolve_location; end

  sig { abstract.returns(T::Array[Graph::Player::Interface]) }
  def resolve_players; end
end
