# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Team`.
# Please instead update this file by running `bin/tapioca dsl Team`.

class Team
  include FrozenRecordAttributeMethods

  module FrozenRecordAttributeMethods
    sig { returns(T.untyped) }
    def location; end

    sig { returns(T::Boolean) }
    def location?; end

    sig { returns(T.untyped) }
    def name; end

    sig { returns(T::Boolean) }
    def name?; end
  end
end
