name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        ruby: ["3.2", "head"]
    steps:
      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cargo-cache: true
          cache-version: v3
          rustup-components: rustfmt,clippy
          rustup-toolchain: stable

      - name: Compile rust ext
        run: bundle exec rake compile

      - name: Run ruby tests
        run: bundle exec rake test

      - name: Run ruby tests with GC stress
        run: bundle exec rake test
        env:
          GC_STRESS: "true"

      - name: Run benchmarks
        run: bundle exec rake bench:all

      - name: Lint ruby
        run: bin/style

      - name: Run ruby typecheck
        run: bin/typecheck

      - name: Tapioca verify gem RBIs
        run: bin/tapioca gem --verify

      - name: Tapioca verify DSL RBIs
        run: bin/tapioca dsl --verify

      - name: Lint rust
        run: cargo clippy -- -D warnings && cargo fmt --check

      - name: Install example ruby dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: example

      - name: Run example ruby tests
        working-directory: example
        run: bundle exec rake test

      - name: Run example ruby typecheck
        working-directory: example
        run: bin/typecheck

      - name: Tapioca verify example gem RBIs
        working-directory: example
        run: bin/tapioca gem --verify

      - name: Tapioca verify example DSL RBIs
        working-directory: example
        run: bin/tapioca dsl --verify
